### ISSUE TITLE
does not work if dialr is not loaded

### ISSUE THREAD

**Issue by renejuan** [socialresearchcentre/dialr#16]
I am not sure if this is due to a namespace issue but I noticed that `dialr` have to be attached before running the `phone` function.

```
x <- "888-8989"
myfunc <- function(x) dialr::phone(x, region = "US")

# This does not work
myfunc(x)
# Error in .jcheck() : No running JVM detected. Maybe .jinit() would help.

# This neither
dialr::phone(x, "US")

# It seems by loading the library before performing any operations the problem
# is resolved.
library(dialr)
dialr::phone(x, "US")
myfunc(x)
```

**Comment by gorcha** [comment]
Hi!

This is because rJava is only initialised when the package is attached with `library()`, but not just when the namespace is loaded (i.e. with the `::` reference).

See `.onAttach()` vs `.onLoad()` here:
https://github.com/socialresearchcentre/dialr/blob/398f2c6664666bdc7d34506d299d87361b2706d5/R/zzz.R#L2-L35

When I originally set up dialr I took this approach based on a couple of other Java wrapper packages, but I'm not sure that it has to be away. I'll try moving everything to `.onLoad()` instead and see if it causes any issues, which should give the behaviour you expect.

**Comment by gorcha** [comment]
Hi @renejuan, I've made this change and it appears to be working fine.
Thanks for the feedback!
